apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-service
  template:
    metadata:
      labels:
        app: mon-service
    spec:
      containers:
      - name: mon-service
        image: damienbat/mon-service:v4  # Replace "utilisateur" with your Docker Hub username
        ports:
        - containerPort: 3000
